import{S as u,i as a}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const s={searchForm:document.querySelector("form"),searchInput:document.querySelector("input"),searchButton:document.querySelector("button"),gallery:document.querySelector(".images"),loader:document.querySelector(".loader")};l();const d=new u(".images a");s.gallery.addEventListener("click",e=>{e.target!==e.currentTarget&&e.preventDefault()});s.searchForm.addEventListener("submit",async e=>{e.preventDefault();const o=e.target.elements.input.value;if(o!==""){f();try{const t=await p(o);s.gallery.innerHTML="",h(t),d.refresh()}catch(t){console.log(t)}finally{l()}}});function f(){s.loader.style.display="block"}function l(){s.loader.style.display="none"}function p(e){const o=`https://pixabay.com/api/?key=42312276-5bc23f4af127c6565aecd0d27&q=${e}`,t={q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0};return fetch(o,t).then(c=>c.json())}function m(e){if(e.hits.length===0){a.show({message:"За запитом нічого не знайдено",color:"red"});return}return e.hits.map(t=>`<li><a href=${t.largeImageURL} ><img src=${t.webformatURL}></a>
  <p>Tags: ${t.tags} </p>
  <p>Likes: ${t.likes} </p>
  <p>Views: ${t.views} </p>
  <p>Comments: ${t.comments} </p>
  <p>Downloads: ${t.downloads} </p>
  
  </li>`).join(`
`)}function h(e){if(e.hits.length===0){a.show({message:"За запитом нічого не знайдено",color:"red"});return}const o=m(e);s.gallery.insertAdjacentHTML("afterbegin",o)}
//# sourceMappingURL=commonHelpers.js.map
