import{S as u,i as l}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const c={searchForm:document.querySelector("form"),searchInput:document.querySelector("input"),searchButton:document.querySelector("button"),gallery:document.querySelector(".images")};a();const d=new u(".images a");c.gallery.addEventListener("click",e=>{e.target!==e.currentTarget&&e.preventDefault()});c.searchForm.addEventListener("submit",e=>{e.preventDefault();const o=e.target.elements.input.value;o!==""&&(f(),p(o).then(t=>{c.gallery.innerHTML="",h(t),a(),d.refresh()}).catch(t=>{console.log(t),a()}))});function f(){const e=document.createElement("span");e.className="loader",document.body.appendChild(e)}function a(){const e=document.querySelector(".loader");e&&e.parentNode&&e.parentNode.removeChild(e)}function p(e){const o=`https://pixabay.com/api/?key=42312276-5bc23f4af127c6565aecd0d27&q=${e}`,t={q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0};return fetch(o,t).then(s=>s.json())}function m(e){return e.hits.length===0?l.show({message:"За запитом нічого не знайдено",color:"red"}):e.hits.map(t=>`<li><a href=${t.largeImageURL} ><img src=${t.webformatURL}></a>
  <p>Tags: ${t.tags} </p>
  <p>Likes: ${t.likes} </p>
  <p>Views: ${t.views} </p>
  <p>Comments: ${t.comments} </p>
  <p>Downloads: ${t.downloads} </p>
  
  </li>`).join(`
`)}function h(e){if(e.hits.length===0)return l.show({message:"За запитом нічого не знайдено",color:"red"});const o=m(e);c.gallery.insertAdjacentHTML("afterbegin",o)}
//# sourceMappingURL=commonHelpers.js.map
